server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/linkpulse
    username: app
    password: app
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update   # Day1~2 동안만 임시. 이후 validate로 바꿔.
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: localhost
      port: 6379

  # Jackson/시간 일관화
  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

# JWT 자리 (Day3에서 채움)
jwt:
  issuer: "linkpulse"
  access-token-ttl-seconds: 900
  refresh-token-ttl-seconds: 1209600
  secret: ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJ


